CREATE TABLE rawdata.user_export (
  id BIGINT,
  first_id STRING,
  second_id STRING,
  p__city STRING,
  p__device_id_list STRING,
  p__is_deleted BIGINT,
  p__name STRING,
  p__province STRING,
  p__signup_time BIGINT,
  p__utm_campaign STRING,
  p__utm_content STRING,
  p__utm_matching_type STRING,
  p__utm_medium STRING,
  p__utm_source STRING,
  p__utm_term STRING,
  p_agentid STRING,
  p_companygroup STRING,
  p_companyindustry1 STRING,
  p_companyindustry2 STRING,
  p_companyname STRING,
  p_companyscale STRING,
  p_companysource STRING,
  p_companytype STRING,
  p_dregetime BIGINT,
  p_gtid STRING,
  p_jgid STRING,
  p_likesport STRING,
  p_money BIGINT,
  p_name STRING,
  p_schooladdress STRING,
  p_some_reach_id STRING,
  p_xmid STRING
)
STORED AS TEXTFILE
LOCATION '/user/impala/data/user_export'
